###############################################################################
PROJECT         = ewaux-dcdc

LIB_DIR         = ../../lib/

GEDATOOLS_DIR   = ~/projects/geda-tools/
GEDALIB_DIR     = ~/projects/geda-lib/

COND_DEFS       =

###############################################################################
include $(GEDATOOLS_DIR)make/gedaflow-defaults.mk
include $(GEDATOOLS_DIR)make/gedaflow.mk
